#!/usr/bin/env bash

sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend 433546_frontend
        bind *:80
        mode http
        default_backend 433546_backend
backend 433546_backend
        balance roundrobin
        server 433546-web-01 100.25.171.179:80 check
        server 433546-web-02 100.25.135.214:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart