#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes

h=0
while ((h <= 12)) ; do
    i=1
    echo "Hour: $h"
    while ((i <= 59)) ; do
        echo $i
        (( i++ ))
    done
    (( h++ ))
done
