#!/usr/bin/env bash
# resolves localhost to 127.0.0.2
# resolves facebook.com to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1.*$/127.0.0.2 \tlocalhost\n8.8.8.8   \tfacebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
