#!/usr/bin/env bash
# resolves localhost to 127.0.0.2
# resolves facebook.com to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8 facebook.com" | tee -a ~/hosts.new
cp -f ~/hosts.new /etc/hosts
