#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

# Change user in Nginx configuration
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change default port to 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Ensure proper permissions are set
chmod 644 /etc/nginx/nginx.conf

# Restart Nginx service
service nginx restart
